name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x build_ipa.sh

      - name: Run build script
        run: ./build_ipa.sh

      - name: Upload xcode.log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: xcode-log
          path: xcode.log
